
exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

collections:
  project_items:
    output: false
  sections:
    output: false
  timeline:
    output: false
  pages:
    output: true
    permalink: /:path/

sass:
  sass_dir: _sass
  style: compressed

# Site settings
show_project_filter: false
url: "edward-rees.com" # the base hostname & protocol for your site
baseurl: ""

# User information
title: Edward Rees
name: "Edward Rees"
avatar_path: "https://edward-rees.com/img/site/er-avatar.png"
job_title: "PhD Candidate at UCL"
github_url: "https://github.com/erees1"
linkedin_url: "https://linkedin.com/in/Rees"
location: "London, UK"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Google analytics
# ga_tracking_id: "UA-XXXX-1"
