exclude:
  - "/bundle/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"
  - "assets/*/README.md"

include:
  - _pages

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

collections:
  project_items:
    output: false
  timeline:
    output: false

sass:
  load_paths:
  - _sass
  style: compressed

# Site settings
url: "https://edward-rees.com" # the base hostname & protocol for your site
baseurl: ""

permalink: /:title

# User information
title: Edward Rees
name: "Edward Rees"
avatar_path: "/assets/img/site/mountain_cropped.JPG"
job_title: "Machine Learning Engineer"
github_url: "https://github.com/erees1"
linkedin_url: "https://linkedin.com/in/Rees"
twitter_url: "https://twitter.com/ERees01"
location: "London, UK"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
